/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Staff;

import Admin.brand;
import db.conn;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author THANUSREE
 */
public class order extends javax.swing.JFrame {
          String id="",quantity;
    conn obj=new conn();
    TableModel td;
 int cnt = 0;
 String[] col = new String[5];
  String[][] data;
   ArrayList<String> customer_listid = new ArrayList<>();
   ArrayList<String> product_listid = new ArrayList<>();
    
      

    /**
     * Creates new form order
     */
    public order() {
        initComponents();
        display();
    }
       
    public void display() {
       

 try {
            String x = "select * from tbl_customer";
            ResultSet rss = obj.select(x);
            String s1, s2;
         
            

            while (rss.next()) {
                s1 = rss.getString("customer_id");
                s2 = rss.getString("customer_name");
                customer_listid.add(s1);
                //System.out.println(cat_listid);                

                customerid.addItem(s2);

            }
 
            String x1 = "select * from tbl_product";
            ResultSet rs4 = obj.select(x1);
            String s3,s4;
         
            

            while (rs4.next()) {
                s3 = rs4.getString("product_id");
                s4 = rs4.getString("product_name");
                product_listid.add(s3);
                //System.out.println(cat_listid);                

                productid.addItem(s4);

            }
            col[0]="order_id";
            col[1] = "customer_id";
            col[2] = "product_id";
            col[3] = "quantity";     
            col[4]="price";


            String sel = "select count(*) from tbl_order";
            ResultSet rs = obj.select(sel);

            if (rs.next()) {
                cnt = rs.getInt(1);
            }

            data = new String[cnt][5];
            String sel1 = "select * from tbl_order";
            ResultSet rs1 = obj.select(sel1);
            int i = 0;

            while (rs1.next()) {
                data[i][0]=rs1.getString("order_id");
               String s= rs1.getString("customer_id");
               String y="select * from tbl_customer where customer_id="+s;
               ResultSet rs5=obj.select(y);
               
               String cname="";
               while (rs5.next()) {
            cname=rs5.getString("customer_name");
               }
             data[i][1]=cname;
                
                String j = rs1.getString("product_id");
                String z="select * from tbl_product where product_id="+j;
                ResultSet rs6=obj.select(z);
                   
               String pname="";
               while (rs6.next()) {
            pname=rs6.getString("product_name");
               }
             data[i][2]=pname;
                data[i][3] = rs1.getString("quantity");
                data[i][4]=rs1.getString("price");

                i++;
            }
            td = new DefaultTableModel(data, col);
            tb11.setModel(td);
        } 
    
 catch (SQLException ex) {
            Logger.getLogger(brand.class.getName()).log(Level.SEVERE, null, ex);
        }

}

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        customerid = new javax.swing.JComboBox();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        Add = new javax.swing.JButton();
        Update = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb11 = new javax.swing.JTable();
        productid = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Customer_id");

        jLabel3.setText("Product_id");

        jLabel4.setText("Quantity");

        jLabel5.setText("Price");

        customerid.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "select" }));
        customerid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customeridActionPerformed(evt);
            }
        });

        Add.setText("Add");
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });

        Update.setText("Update");
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });

        Delete.setText("Delete");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });

        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        tb11.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb11MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb11);

        productid.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "select" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE))
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField4)
                            .addComponent(jTextField3)
                            .addComponent(customerid, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(productid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Add)
                        .addGap(18, 18, 18)
                        .addComponent(Update)
                        .addGap(36, 36, 36)
                        .addComponent(Delete)
                        .addGap(29, 29, 29)
                        .addComponent(clear)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 40, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customerid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(productid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Add)
                    .addComponent(Update)
                    .addComponent(Delete)
                    .addComponent(clear))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void customeridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customeridActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customeridActionPerformed

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
        // TODO add your handling code here:
          String s1 = jTextField3.getText();
                    String s2 = jTextField4.getText();

        if (s1.equals("")) {
            JOptionPane.showMessageDialog(this, "insert order details");

        } else {
            int x = customerid.getSelectedIndex();
             String ss=customer_listid.get(x-1);
//            System.out.println(ss);
            int x1 = productid.getSelectedIndex();
             String sb=product_listid.get(x-1);
//            System.out.println(ss);
          try{
              String ins="insert into tbl_order(customer_id,product_id,quantity,price) values('"+ss+"','"+sb+"','"+s1+"','"+s2+"')";
             // System.out.println(ins);
              boolean b=obj.insert(ins);
              display();
          }
      
      
          catch(Exception e)
          {
              
          }
      }

    }//GEN-LAST:event_AddActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        jTextField3.setText(""); 
        jTextField4.setText(""); 
    }//GEN-LAST:event_clearActionPerformed

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        // TODO add your handling code here:
         quantity = jTextField3.getText();

        String up = "update tbl_order set quantity='" + quantity + "' where order_id=" + id + "";
        boolean b = obj.insert(up);

        display();     
    }//GEN-LAST:event_UpdateActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        // TODO add your handling code here:
          String del = "delete from tbl_order where order_id='" + id + "'";
        boolean b = obj.insert(del);
        if (b == true) {

            JOptionPane.showMessageDialog(this, "Sucessfully Deleted");
            display();

        } else {
            JOptionPane.showMessageDialog(this, "Not Deleted");
        }
        System.out.println(del);


    }//GEN-LAST:event_DeleteActionPerformed

    private void tb11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb11MouseClicked
        // TODO add your handling code here:
         int row=tb11.getSelectedRow();
         id=tb11.getValueAt(row,0).toString();
         
       String order_id = td.getValueAt(row, 0).toString();
        String customer_id = td.getValueAt(row, 1).toString();
        String product_id = td.getValueAt(row, 2).toString();
        String quantity = td.getValueAt(row, 3).toString();
        String price = td.getValueAt(row, 4).toString();
        
        customerid.setSelectedItem(customer_id);
        productid.setSelectedItem(product_id);
        
       jTextField3.setText(quantity);
         jTextField4.setText(price);
         
    }//GEN-LAST:event_tb11MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new order().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JButton Delete;
    private javax.swing.JButton Update;
    private javax.swing.JButton clear;
    private javax.swing.JComboBox customerid;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JComboBox productid;
    private javax.swing.JTable tb11;
    // End of variables declaration//GEN-END:variables
}
