/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Admin;
import db.conn;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
/**
 *
 * @author user
 */
public class category extends javax.swing.JFrame {

    static int getSelectedIndex() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * Creates new form category
     */
    String id="",cname="";
    conn obj=new conn();
    TableModel td;
 int cnt = 0;
 String[] col = new String[2];
  String[][] data;
  
    public category() throws SQLException {
        initComponents();
        col[0] = "Slno";
            col[1] = "Category";
           
           


            String sel = "select count(*) from tbl_category";
            ResultSet rs = obj.select(sel);
            if (rs.next()) {
                cnt = rs.getInt(1);
            }
          data =new String[cnt][2];
            String sel1="select * from tbl_category";
            ResultSet rs1=obj.select(sel1);
            int i=0;

            while(rs1.next())
            {
                data[i][0]=rs1.getString("Category_id");
                data[i][1]=rs1.getString("Category_name");
                
                i++;
            }
            
            td=new DefaultTableModel(data,col);
            tb1.setModel(td);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        Add = new javax.swing.JButton();
        Update = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        Cancel = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Category");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        Add.setText("Add");
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });

        Update.setText("Update");
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });

        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        Cancel.setText("clear");
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });

        tb1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        tb1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Add)
                        .addGap(69, 69, 69)
                        .addComponent(Update))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(delete)
                        .addGap(70, 70, 70)
                        .addComponent(Cancel)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(230, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Cancel)
                            .addComponent(delete)
                            .addComponent(Update)
                            .addComponent(Add))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(108, 108, 108))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        try {
            // TODO add your handling code here:
            
            
            String del = "delete from tbl_category where Category_id='" + id + "'";
           boolean b= obj.insert(del);
           if(b==true)
              {
                
                  JOptionPane.showMessageDialog(this, "Sucessfully Deleted");
                  
              }else{
                  JOptionPane.showMessageDialog(this, "Not Deleted");
              }  
            System.out.println(del);
             col[0] = "Slno";
              col[1] = "Category";
              
              String sel1="select * from tbl_category";
              ResultSet rs1=obj.select(sel1);
              int i=0;
              
              while(rs1.next())
              {
                  data[i][0]=rs1.getString("Category_id");
                  data[i][1]=rs1.getString("Category_name");
                  
                  i++;
              }
              
              
              String sel = "select count(*) from tbl_category";
              ResultSet rs = obj.select(sel);
              if (rs.next()) {
                  cnt = rs.getInt(1);
              }
              data =new String[cnt][2];
              td=new DefaultTableModel(data,col);
            tb1.setModel(td);
            } catch (Exception ex) {
                Logger.getLogger(category.class.getName()).log(Level.SEVERE, null, ex);
       
    }//GEN-LAST:event_deleteActionPerformed
    }
    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
        // TODO add your handling code here:
        jTextField1.setText("");
    }//GEN-LAST:event_CancelActionPerformed

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
      String s1= jTextField1.getText();
      if(s1.equals(""))
            {
                JOptionPane.showMessageDialog(this, "insert Category");

            }else{
          try {
              String ins="insert into tbl_category(Category_name) values('"+s1+"')";
              //System.out.println(ins);
              boolean b=obj.insert(ins);
              col[0] = "Slno";
              col[1] = "Category";
              
              
              
              String sel = "select count(*) from tbl_category";
              ResultSet rs = obj.select(sel);
              if (rs.next()) {
                  cnt = rs.getInt(1);
              }
              data =new String[cnt][2];
              String sel1="select * from tbl_category";
              ResultSet rs1=obj.select(sel1);
              int i=0;
              
              while(rs1.next())
              {
                  data[i][0]=rs1.getString("Category_id");
                  data[i][1]=rs1.getString("Category_name");
                  
                  i++;
              }
              
              td=new DefaultTableModel(data,col);
              tb1.setModel(td);
              if(b==true)
              {
                  JOptionPane.showMessageDialog(this, "Sucessfully Inserted");
                  jTextField1.setText("");
                  
              }else{
                  JOptionPane.showMessageDialog(this, "Not Inserted");
              }    }
// TODO add your handling code here:
          catch (SQLException ex) {
              Logger.getLogger(category.class.getName()).log(Level.SEVERE, null, ex);
          }
     }
    }//GEN-LAST:event_AddActionPerformed

                 
    private void tb1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb1MouseClicked
        // TODO add your handling code here:
        int row=tb1.getSelectedRow();
        System.out.println(row);
        id=td.getValueAt(row,0).toString();
        cname=(String)td.getValueAt(row,1);
        
        jTextField1.setText(cname);
//        txt_pass.setText(pass1);
//        btn_sub.setVisible(false);
        
        
        
    }//GEN-LAST:event_tb1MouseClicked

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        // TODO add your handling code here:
        try{
        cname = jTextField1.getText();
           
            String up = "update tbl_category set Category_name='" + cname + "' where Category_id=" + id + "";
           boolean b= obj.insert(up);
        
            col[0] = "Slno";
              col[1] = "Category";
              
              
              
              String sel = "select count(*) from tbl_category";
              ResultSet rs = obj.select(sel);
              if (rs.next()) {
                  cnt = rs.getInt(1);
              }
              data =new String[cnt][2];
              String sel1="select * from tbl_category";
              ResultSet rs1=obj.select(sel1);
              int i=0;
              
              while(rs1.next())
              {
                  data[i][0]=rs1.getString("Category_id");
                  data[i][1]=rs1.getString("Category_name");
                  
                  i++;
              }
              
              td=new DefaultTableModel(data,col);
              tb1.setModel(td);
              if(b==true)
              {
                  JOptionPane.showMessageDialog(this, "Sucessfully Inserted");
                  
              }else{
                  JOptionPane.showMessageDialog(this, "Not Inserted");
              }    }
        catch(Exception ee){}
    }//GEN-LAST:event_UpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(category.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(category.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(category.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(category.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new category().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(category.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JButton Cancel;
    private javax.swing.JButton Update;
    private javax.swing.JButton delete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable tb1;
    // End of variables declaration//GEN-END:variables
}
